### ISSUE TITLE
Rate ticket when closed

### ISSUE THREAD

**Issue by KarlOfDuty** [KarlOfDuty/SupportBoi#12]

**Comment by KarlOfDuty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gamify support](https://trello.com/c/UO0DaD2h/14-gamify-support)

**Comment by Emil8250** [comment]
I've taken a quick look at this -  Were you thinking a 1-5 rating? 
I've stored the result in ticket_history in a rating column.
![Capture](https://user-images.githubusercontent.com/12008922/76440267-e2026d00-63bd-11ea-87a3-0e936a6c8b72.PNG)

**Comment by KarlOfDuty** [comment]
Yep, looks good! Might want to attach the transcript to that message so the response is easily viewable.

**Comment by Emil8250** [comment]
That should still be attached, I just cropped it out of the snapshot :)
