### ISSUE TITLE
Semi/bug maybe?

### ISSUE THREAD

**Issue by Jakethesnkae** [KarlOfDuty/SupportBoi#20]
Ayo, I was wondering what'd be the easiest way to fix this error 
```bash
  at DSharpPlus.DiscordClient.InternalUpdateGatewayAsync()
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync()
   --- End of inner exception stack trace ---
   at DSharpPlus.DiscordClient.ConnectAsync()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by KarlOfDuty** [comment]
Could you give some more information about the issue?

**Comment by Jakethesnkae** [comment]
What are you requesting exactly sorta confused do ya have discord?

**Comment by KarlOfDuty** [comment]
Like what were you doing, when did it happen, how often does it happen. I do have discord, its linked in the readme.

**Comment by KarlOfDuty** [comment]
Although the discord button seems to have trouble loading right now but the link appears if you wait a bit.

**Comment by Jakethesnkae** [comment]
I went ahead and put in the mysql info, then bot ID Id's needed for Category's and stuff, Then it outputted that error. I also did install .Net core 2.2 as specified

**Comment by KarlOfDuty** [comment]
It looks like it wasnt able to connect to discord.

**Comment by Jakethesnkae** [comment]
I found what the issue, (after alot of reworking things) was we're good!

**Comment by KarlOfDuty** [comment]
Nice, what was it?
