### ISSUE TITLE
Additional reaction functions

### ISSUE THREAD

**Issue by idblock** [KarlOfDuty/SupportBoi#27]
Hello, i would like to create a message with a react emoji ALREADY on (or to add)

I do not wish use a message AND react to this message

**Comment by KarlOfDuty** [comment]
I'm not really sure what you mean?

**Comment by idblock** [comment]
I mean i would like to add on a message ( unless the bot create it ) and users can react with an emoji on it to open ticket, save transcript with react, close too with react

**Comment by KarlOfDuty** [comment]
You mean that the first message in the ticket should have those reaction buttons?

**Comment by idblock** [comment]
Yes, imagine that ticket emoji "🎫" was put by bot and he check who react, if user react open ticket 👍 

maybe add an system with this to not create x2000 tickets for a user, set a limit in config ?

**Comment by almir101** [comment]
Is this feature implemented?

**Comment by KarlOfDuty** [comment]
It is not.
