### ISSUE TITLE
Suggestion: addstaff adds user to tickets 

### ISSUE THREAD

**Issue by FutureLemon** [KarlOfDuty/SupportBoi#44]
I think it would be cool if people who are added as staff are also added to the category settings and thus any future opened tickets.

**Comment by KarlOfDuty** [comment]
It would be a fairly major system to add for no real benefit as far as I can see. The bot going around adding user permissions could also be bad for security if executed by someone who doesn't realise the command will set a bunch of permissions on future channels and all perm inheriting channels.
