### ISSUE TITLE
Suggestion: -name

### ISSUE THREAD

**Issue by FutureLemon** [KarlOfDuty/SupportBoi#46]
A quick and easy command to name tickets would be pretty neat and useful.

**Comment by KarlOfDuty** [comment]
Isn't is just easier to rename it normally?

**Comment by FutureLemon** [comment]
> Isn't is just easier to rename it normally?

I've found to mass rename tickets it goes quite easy copying the -name command and then typing in the name and quickly going through every ticket. I guess in a way it's just personal prefference.

**Comment by KarlOfDuty** [comment]
Whoops wrong id
