### ISSUE TITLE
Bump DiscordChatExporter to 2.26+ in releases

### ISSUE THREAD

**Issue by jkmartindale** [KarlOfDuty/SupportBoi#51]
Ticket transcripts currently format replies as regular messages, which can be confusing sometimes. DiscordChatExporter 2.26 added replies formatting to its exports.

**Comment by KarlOfDuty** [comment]
Yeah I've had this as a todo for some time but iirc they changed it a lot since the version I imported, so its not a very straight forward update. I'll get to it when I have some extra time on my hands.
