### ISSUE TITLE
Discord Buttons

### ISSUE THREAD

**Issue by chelminski** [KarlOfDuty/SupportBoi#53]
I would like you to add Discord buttons 
- create new chat
- confirm close chat

![image](https://user-images.githubusercontent.com/62246121/147015872-cd45d08d-d4a8-446b-9c73-d791cb19a9fa.png)

More info:
https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons

**Comment by KarlOfDuty** [comment]
I'll have to look into if this is possible, where exactly do you want the buttons to be?

**Comment by chelminski** [comment]
It's nice if it was possible to leave a button under the message. For example, in my case it is a message on the support channel.
![image](https://user-images.githubusercontent.com/62246121/147230588-dfad85d6-8d9f-4b74-9a4d-4434d82f8864.png)
 
**--**
I would place the second button under the message confirming that the chat is closed. For example:

- !close
- Your chat will be closed and cannot be reopened. The support channel will be removed! Do you want to confirm closing the chat?
![image](https://user-images.githubusercontent.com/62246121/147231172-ad2c0d3d-2177-41ea-8d4b-7a1cf46f4527.png)
