### ISSUE TITLE
Update to built-in command system

### ISSUE THREAD

**Issue by chelminski** [KarlOfDuty/SupportBoi#55]
I would like you to add the ability to execute commands with the Discord listener.

![image](https://user-images.githubusercontent.com/62246121/147016397-a89ed7df-1959-48dc-8fe0-cc2529d7ab88.png)

More info: 
https://discord.com/developers/docs/interactions/application-commands

**Comment by KarlOfDuty** [comment]
I don't think that is possible with this api but I can double check

**Comment by KarlOfDuty** [comment]
It was added to the api I use a few months after this post. I think I will implement something for this in the next update.
