### ISSUE TITLE
/rename

### ISSUE THREAD

**Issue by Veyronity** [KarlOfDuty/SupportBoi#83]
Without changing the Ticket's original name

For example
in #ticket-00001
/rename needs admin
will make it #ticket-00001-needs-admin
and if /rename (no arguments) it will reset name back to #ticket-00001

**Comment by KarlOfDuty** [comment]
I don't think this is a great solution, putting information about the ticket in the channel name would be a breach of security as anyone can read channel names. It is much better to move tickets between categories in order to show pre-defined information about them in the sidebar.
