### ISSUE TITLE
Summary Internal Error

### ISSUE THREAD

**Issue by docwhomc** [KarlOfDuty/SupportBoi#9]
`-summary` resulted in "Internal error occured, please report this to the developer."

![image](https://user-images.githubusercontent.com/53803582/65560149-76aa0900-df0b-11e9-9021-ea3a82c457b3.png)

Occurred in: https://discordapp.com/channels/571042222754103308/624791896266375169/

**Comment by docwhomc** [comment]
![image](https://user-images.githubusercontent.com/53803582/65560596-59763a00-df0d-11e9-9538-5634cbf997c7.png)

Occurred in: https://discordapp.com/channels/571042222754103308/625600848243851264

**Comment by docwhomc** [comment]
It appears that `-summary` fails in some cases if the ticket doesn't have a summary yet.

**Comment by docwhomc** [comment]
![image](https://user-images.githubusercontent.com/53803582/65560654-84608e00-df0d-11e9-960e-72baf9bca50e.png)

It is assigned to staff though.

**Comment by docwhomc** [comment]
![image](https://user-images.githubusercontent.com/53803582/65561243-bffc5780-df0f-11e9-94bb-168df8918629.png)

https://discordapp.com/channels/571042222754103308/623678192405970944

**Comment by docwhomc** [comment]
![image](https://user-images.githubusercontent.com/53803582/65561278-ddc9bc80-df0f-11e9-94d5-c7d05fdcbbe2.png)

**Comment by docwhomc** [comment]
So it looks like summary throws an error if it hasn't been set yet, instead of saying that there isn't a summary.

**Comment by KarlOfDuty** [comment]
Resolved.
